### ISSUE TITLE
Good Work!

### ISSUE THREAD

**Issue by 0xScratch** [nikhilkulkarni1755/BiasDetector#1]
Just going through all the finalists of Backdrop Build v3, and hopped into your project. Tbh, It was a good starter project and a cool usage of TensorFlow.
It be good if you try to organize that README in a good way which might make it easy for users to know how it's built and the steps one can follow to get started with your project. Looking for what you gonna bring in v4...Good Luck!

**Comment by nikhilkulkarni1755** [comment]
thank you so much! 

Things to add to README:
1) I used pyenv to get tf running locally. maybe a link to help others start. 
2) how to run this project. One file trains the model; the other can be used to predict. 
3) Still figuring out tensorflow-serving. Will add steps to deploy. 
4) [the article](https://medium.com/@nikhilkulkarni1755/learning-tensorflow-lets-build-a-text-classification-tool-in-tensorflow-aa538a3bdec4) and [the demo](https://youtu.be/-F4fRZNkitE)
